# name: Actions practice 1
# on: push
# jobs:
#   actions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download code
#         uses: actions/checkout@v3
#       - name: Install dependencies
#         run: npm ci
#       - name: Linting script
#         run: npm run lint
#       - name: Test code
#         run: npm run test
#       - name: Build script
#         run: npm run build
#       - name: Deployment dummy
#         run: echo "Deploying..."

name: Deployment Exercise 2
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:J
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..."
