name: Actions practice 1
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Linting script
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build script
        run: npm run build
      - name: Deployment dummy
        run: echo "Deploying..."
